server:
  port: 80
spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:mysql:///dbpms?serverTimezone=GMT%2B8&characterEncoding=utf8
    username: root
    password:
  thymeleaf:
    prefix: classpath:/templates/modules/
    suffix: .html
    cache: false

mybatis:
  mapper-locations: classpath:/mapper/*/*.xml

logging:
  level:
    com.cy: debug

shiro:
   loginUrl: /doLoginUI
